---
title: "Teaching"
output: 
  html_document:
    css: css/styles.css
---
<!--html_preserve-->

<head>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&family=Roboto+Slab:wght@300;400;700&family=Lora:wght@400;600;700&family=Cormorant+Garamond:wght@400;600;700&family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
</head>

<style>
.teaching-container {
  max-width: 800px;
  margin: 20px auto;
  padding: 20px;
}

h1, h2, h3 {
  color: #333;
}

ul {
  list-style-type: disc;
  margin-left: 20px;
}

ul li {
  margin-bottom: 10px;
}
</style>


<div class="teaching-container">

  <h3>Massachusetts Institute of Technology</h3>
  <ul>
    <li>Math Camp for Incoming Graduate Students, Co-Instructor, Fall 2024</li>
    <li>Quantitative Research Methods II -- Causal Inference (Graduate, 6.7/7.0), Teaching Assistant, Spring 2024</li>
  </ul>

  <h3>Education University of Hong Kong</h3>
  <ul>
    <li>Pedagogical Training: I received a Bachelor of Social Science Education degree from the Education University of Hong Kong, where I was trained in social science education and pedagogy. This training included methods for engaging students and teaching foundational social science concepts effectively.</li>
    <li>Mock Teaching Experience: During my undergraduate studies, I participated in in-class mock teaching exercises, where I taught basic social science concepts to peers under the guidance of experienced educators.</li>
  </ul>
</div>
  

<!--html_preserve-->

